### ISSUE TITLE
Parallel or Nah?

### ISSUE THREAD

**Issue by AutoSponge** [WebReflection/node-worker#1] opened 2017-08-02 13:11 UTC
I read this in the docs:

> Note: Using the timeout or breakOnSigint options will result in new event loops and corresponding threads being started, which have a non-zero performance overhead.

I scanned the code and I didn't see either setting in `createSandbox`. Is there something else happening to ensure parallel processing? Or do all the vm's share a thread?

Thanks for highlighting a use case for this api.

**Comment by WebReflection** [comment] 2017-08-02 14:04
The use case for this API is having NodeJS driven WebServer / IoT capabilities without needing Electron.

This project was born yesterday after this very annoying situation:
https://github.com/WebReflection/benja/issues/22#issuecomment-319614019

Electron ships incapable of using the OS nodejs version, causing a lot of pain when it comes to native/compiled modules:
  * you cannot have both system and electron sharing the same `node_modules` project folder
  * you need to recompile here or there whenever a module gets updated in both OS and Electron

You end up with two modules, one usable by the system and one usable by Electron.

On top of that, Electron doesn't understand regular nodejs/system paths.

**This API solves all of this** and it makes it possible to delegate to the OS version of nodejs any sort of operation, also keeping external workers _both_ reusable/testable in isolation (just provide an `onmessage` and `postMessage` stub) and on top of that:

  * it makes it possible to ditch Xorg entirely, running NodeJS via WebKitGTK+ (as example) on Wayland
  * it makes it possible to have Electron-like applications even on Raspberry Pi 1 / Zero / WiFi (testing as I'm writing)
  * it separates DOM from NodeJS concerns. It provides a mechanism that if it's good for Web Workers in general, can be same good if not better for NodeJS.

That being said, I haven't understood your first question.

What do you want me to do? Maybe a PR? Maybe a link to explain?

I'm not sure I'm following.

Thanks for improving this "_issue_" whatever it is about.

**Comment by WebReflection** [comment] 2017-08-02 20:42
after reading those mentioned parts of the documentation, I feel like I can close this ticket as it's not a bug, just a question.

This project aim is **not public websites** but Internet of Things related projects.

You are in charge of your own workers, there's nothing to kill, close, or timeout about here.

**Closed as completed by WebReflection** 2017-08-02 20:42 UTC
Labels: question
